### PR TITLE
Ho ho ho

### PR DESCRIPTION
**Pull request by NicolasDP**
# Merry Christmas

Now all new code must comply with default rust format.

i.e.:

```
rustup component add rustfmt-preview
cargo fmt
cargo fmt -- --check
```

### CODE REVIEW

**Comment by NicolasDP** [comment]
Obviously it is the day we push new coding style the CI is having a problem with nightly....

**Comment by sjmackenzie** [comment]
probably best to avoid these code formatters, as they hide code smell.

**Comment by NicolasDP** [comment]
this is a general move for all of our rust projects. as code grow we need to allow consistency. The advantage is that rustfmt is consistent, stable and is easy to automatise

**Comment by sjmackenzie** [comment]
Understood, it doesn't bother me it's just I argue that code formatters put santa's face back on, hiding the octopus faced monster. So when sane people come along they won't get alerted to potentially bad code which sticks out like a sore thumb exhibited by dodgy indentation or weird case statement formatting etc. I'm trying to say it's good for sherlock holmes to investigate a pristine crime scene where telltale clues haven't been formatted away. :-)

**Pull request merged**
