### PR TITLE
enable building with nix

### PR DESCRIPTION
**Pull request by cleverca22**

### CODE REVIEW

**Comment by rvl** [comment]
The following things would also need to be done:
- A little documentation at the top of `default.nix`.
- Instructions on how to update `cargoSha256`.
- Add the nix-build to CI so that it doesn't bitrot.
- Use `lib.filterSourceWith` to remove the `target` directory (`fetchgit ./.` doesn't work because of submodules).
- Use a stable nixos channel, or pin to a git revision.

**Comment by disassembler** [comment]
Might I suggest we use iohk-nix for pinning and filtering source @rvl @cleverca22?

**Comment by mzabaluev** [comment]
cc @edolstra

**Comment by NicolasDP** [comment]
If you wish to utilise a pre-built binary, please have a look at the release directory: https://github.com/input-output-hk/cardano-cli/releases

**Pull request closed without merging**
